// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBghg90vv5FQVg2yvEr2SRkP7COSGdioY',
    appId: '1:116340087978:web:7f4d0c7490443e03bd84d3',
    messagingSenderId: '116340087978',
    projectId: 'my-todo-edd2f',
    authDomain: 'my-todo-edd2f.firebaseapp.com',
    storageBucket: 'my-todo-edd2f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApCX-pypBPAwXrvQwpPfnccwkmx8LipfU',
    appId: '1:116340087978:android:2589cadb44fc4a8fbd84d3',
    messagingSenderId: '116340087978',
    projectId: 'my-todo-edd2f',
    storageBucket: 'my-todo-edd2f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALnz7yDH9afeHh-ih_10FFLXbDKUmPHac',
    appId: '1:116340087978:ios:c7a1f9953e3d9a20bd84d3',
    messagingSenderId: '116340087978',
    projectId: 'my-todo-edd2f',
    storageBucket: 'my-todo-edd2f.appspot.com',
    iosClientId: '116340087978-j7cfp6n5a8pjnqu0nm4157opgfburp9m.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALnz7yDH9afeHh-ih_10FFLXbDKUmPHac',
    appId: '1:116340087978:ios:c7a1f9953e3d9a20bd84d3',
    messagingSenderId: '116340087978',
    projectId: 'my-todo-edd2f',
    storageBucket: 'my-todo-edd2f.appspot.com',
    iosClientId: '116340087978-j7cfp6n5a8pjnqu0nm4157opgfburp9m.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp',
  );
}
